// src/react/src/App.js
import React, { Component } from 'react';
import { Link, Route, Switch } from 'react-router-dom'

import './App.css';

import AboutPage from './pages/AboutPage';
import ConnectPage from './pages/ConnectPage';
import HomePage from './pages/HomePage';
import SkillsPage from './pages/SkillsPage';


class App extends Component {
  render() {
    return (
      <div className="App">
        <h1>React</h1>
        <Link to='/about'>about </Link> 
        <Link to='/connect'>connect </Link> 
        <Link to='/home'>home </Link> 
        <Link to='/skills'>skills </Link> 

        <Switch>
          <Route path='/about' component={AboutPage}/>
          <Route path='/connect' component={ConnectPage}/>
          <Route path='/home' component={HomePage}/>
          <Route path='/skills' component={SkillsPage}/>
        </Switch>
      </div>
    );
  }
}

export default App;

// src/vue/src/App.vue
<template>
  <div id="app">

    <h1>Vue</h1>

    <router-link :to="{ path: 'about'}">about</router-link>
    <router-link :to="{ path: 'connect'}">connect</router-link>
    <router-link :to="{ path: 'home'}">home</router-link>
    <router-link :to="{ path: 'skills'}">skills</router-link>
    <router-view/>
    
  </div>
</template>

<script>
export default {
  name: 'App'
}
</script>

<style>
</style>
